[colors.bright]
black = "0x666666"
blue = "0x819AFF"
cyan = "0x66D9EF"
green = "0xA6E22E"
magenta = "0xAE81FF"
red = "0xF92672"
white = "0xF8F8F2"
yellow = "0xE2E22E"

[colors.normal]
black = "0x333333"
blue = "0x6A7EC8"
cyan = "0x56ADBC"
green = "0x86B42B"
magenta = "0x8C6BC8"
red = "0xC4265E"
white = "0xE3E3DD"
yellow = "0xB3B42B"

[colors.primary]
background = "0x1B1D1E"
foreground = "0xF8F8F2"
