[colors.bright]
black = "0x625e4c"
blue = "0x9d65ff"
cyan = "0x58d1eb"
green = "0x98e024"
magenta = "0xf4005f"
red = "0xf4005f"
white = "0xf6f6ef"
yellow = "0xe0d561"

[colors.normal]
black = "0x1a1a1a"
blue = "0x9d65ff"
cyan = "0x58d1eb"
green = "0x98e024"
magenta = "0xf4005f"
red = "0xf4005f"
white = "0xc4c5b5"
yellow = "0xfa8419"

[colors.primary]
background = "0x1a1a1a"
foreground = "0xc4c5b5"
