
" The system menu file includes a "Buffers" menu and this disable it
let no_buffers_menu=1

" Size of gVim window
set lines=999 columns=140

"autocmd GUIEnter * winpos 100 50

" https://superuser.com/questions/10588/how-to-make-cut-copy-paste-in-gvim-on-ubuntu-work-with-ctrlx-ctrlc-ctrlv
source $VIMRUNTIME/mswin.vim
behave mswin
" Use system's clipboard
set clipboard=unnamed

