
" The system menu file includes a "Buffers" menu and this disable it
let no_buffers_menu=0

" Size of gVim window
set lines=999 columns=140

"autocmd GUIEnter * winpos 100 50

" https://superuser.com/questions/10588/how-to-make-cut-copy-paste-in-gvim-on-ubuntu-work-with-ctrlx-ctrlc-ctrlv
source $VIMRUNTIME/mswin.vim
behave mswin
" Use system's clipboard
set clipboard=unnamed

" scrooloose/nerdtre
" open a NERDTree automatically when vim starts up
"autocmd vimenter * NERDTree
" Click on an open window/buffer, and have that file highlighted in the NERDTree (ref01).
"autocmd BufEnter * if &modifiable | NERDTreeFind | wincmd p | endif


" References
" ref01 https://superuser.com/a/474298/766943
