# #dotfiles: dst=$XDG_CONFIG_HOME/starship.toml
# Based on https://starship.rs/presets/catppuccin-powerline (catppuccin_latte)

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = '[▶](bright-black) '

format = """
$os\
$username\
$sudo\
$hostname\
[](bg:dir_bg fg:os_bg)\
$directory\
[](bg:git_bg fg:peach)\
$git_branch\
$git_status\
[](fg:git_bg bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ ](fg:green)\
$line_break\
$character"""

right_format = """
[](fg:right_bg)\
$kubernetes\
$jobs\
$status\
$cmd_duration\
$time"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = 'p10k'

[os]
disabled = false
style = "bg:os_bg fg:left_fg"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_user = "bg:red fg:left_fg"
style_root = "bg:red fg:left_fg"
format = '[ $user]($style)'

[sudo]
disabled = false
format = '[$symbol]($style)'
style = "bg:red fg:left_fg"

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = "…/"
# I think this isn't working
fish_style_pwd_dir_length = 3
# Whether or not to truncate to the root of the git repo that you're currently in.
truncate_to_repo = false
# style = "fg:bold h1 bg:left_bg"
style = "bg:dir_bg fg:left_fg"
# I think this isn't working
before_repo_root_style = 'fg:h5'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
# "dev" = "󰲋"

[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch ](fg:left_fg bg:git_bg)]($style)'

[git_status]
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:left_fg bg:git_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:left_fg bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:left_fg bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:left_fg bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:left_fg bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[time]
disabled = false
time_format = "❮ %T"
style = "fg:#5f8787 bg:right_bg"
format = '[ $time  ]($style)'

[cmd_duration]
show_milliseconds = true
format = "[❮ $duration ]($style)"
style = "fg:h5 bg:right_bg"
disabled = false
show_notifications = false
# Shortest duration for notification (in milliseconds)
min_time_to_notify = 10_000

[kubernetes]
disabled = false
style = "bg:right_bg"

[status]
disabled = false
format = '[$symbol$status]($style)'
success_symbol = ""
style = "fg:green bg:right_bg"
failure_style = "bold red bg:right_bg"

[palettes.p10k]
os_bg = "#d20f39"
red = "#d20f39"
peach = "#c84e08"
yellow = "#df8e1d"
green = "#40a02b"
sapphire = "#209fb5"
lavender = "#7287fd"
left_fg = "#dce0e8"
dir_fg = "#FFFFFF"
dir_bg = "#c84e08"
git_bg = "#079040"
h1 = "#0d8ec9"
h5 = "#a7a7a7"
left_bg = "#303030"
right_bg = "#303030"
right_fg = "#5e8585"
