# Scheme: Monokai Dark (blue/cyan modified)
# Default colors
  primary:
    background: '0x272822'
    foreground: '0xF8F8F2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x272822'
    red:     '0xF92672'
    green:   '0xA6E22E'
    yellow:  '0xF4BF75'
    blue:    '0xF8F8F2'
    magenta: '0xAE81FF'
    cyan:    '0x08a4a7'
    white:   '0xF8F8F2'

  # Bright colors
  bright:
    black:   '0x75715E'
    red:     '0xF92672'
    green:   '0xA6E22E'
    yellow:  '0xF4BF75'
    blue:    '0x66D9EF'
    magenta: '0xAE81FF'
    cyan:    '0xA1EFE4'
    white:   '0xF9F8F5'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
    #black:   '0x333333'
    #red:     '0xf2777a'
    #green:   '0x99cc99'
    #yellow:  '0xffcc66'
    #blue:    '0x6699cc'
    #magenta: '0xcc99cc'
    #cyan:    '0x66cccc'
    #white:   '0xdddddd'

